[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pkg"
license = { text = "Apache License, Version 2.0" }
dynamic = ["version"]
description = "Testing semver actions"


[tool.setuptools.dynamic]
version = { attr = "pkg.__version__" }
